import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import SlideCard from "../components/SlideCard";
import SmallCards from "../components/SmallCards";
import styles from "../styles/Home.module.css";


export default function Home({ exploreData, liveAnyData }) {
  
  const data = JSON.parse(exploreData).explore;
  const LiveData = JSON.parse(liveAnyData).live;
  
  return (
    <div className="">
      <Head>
        <title>Airbnb__Clone_1.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Banner */}
      <Banner />

      <main className="max-w-7xl mx-auto sm:px-16">
        {/* Explore NearBy */}
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore NearBy</h2>

          {/* pull data from server */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {data.map((item, index) => (
              <SmallCards key={index} item={item} />
            ))}
          </div>
        </section>

        {/* Live Anywhere */}

        <section className="pt-6">
          <h2 className="text-4xl font-semibold py-8">Live AnyWhere</h2>
          <div className="flex space-x-3 overflow-scroll w-full scrollbar-hide p-3 -ml-3">
            {LiveData?.map((card, index) => (
              <SlideCard key={index} card={card} />
            ))}
          </div>
        </section>

        <LargeCard
          title="The Greatest Outdoors"
          desc="Wishlist curated by Airbnb"
          buttonText="Get Inspired"
          img="https://images.unsplash.com/photo-1593351415075-3bac9f45c877?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8Ym9hdHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"
        />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("http://localhost:3000/api/staticdata").then(
    (res) => res.json()
  );

  const liveAnyData = await fetch("http://localhost:3000/api/liveany").then(
    (res) => res.json()
  );
  return {
    props: {
      exploreData,
      liveAnyData,
    },
  };
}
